name: Update awesome list

on: 
  workflow_dispatch:
  schedule:
    - cron: '00 00 */1 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Awesome generator
        uses: simonecorsi/mawesome@v2
        with:
          api-token: ${{ secrets.API_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-email: volodymyr@foxmail.com
          github-name: ${{ github.repository_owner }}
